#!/usr/bin/env bash
set -euo pipefail

# Text-only Qwen3 CoT cold-start before RCPC/ROPD RL.

set -x

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"

export PYTHONUNBUFFERED=1
export TOKENIZERS_PARALLELISM="${TOKENIZERS_PARALLELISM:-false}"
export PYTORCH_CUDA_ALLOC_CONF="${PYTORCH_CUDA_ALLOC_CONF:-expandable_segments:True}"
# Model and data. MODEL_PATH is a Hugging Face repo id by default; override it
# with a local base-model/SFT checkpoint path only when you want local weights.
MODEL_PATH="${MODEL_PATH:-Qwen/Qwen3-4B-Instruct-2507}"
TRAIN_FILE="${TRAIN_FILE:-/mnt/bn/chenhaobo-va-data/lrj/data/WebInstruct-verified/train_5k_cot.jsonl}"
VAL_FILE="${VAL_FILE:-}"

# Checkpoint output and resume. RESUME_FROM_CHECKPOINT can be:
#   empty  -> train from MODEL_PATH
#   auto   -> resume from latest checkpoint-* under OUTPUT_DIR
#   path   -> resume from that exact Trainer checkpoint directory
OUTPUT_DIR="${OUTPUT_DIR:-/mnt/bn/chenhaobo-va-data/lrj/checkpoints/rcpc/qwen3-4b-webinstruct-cot-sft}"
RESUME_FROM_CHECKPOINT="${RESUME_FROM_CHECKPOINT:-}"
OVERWRITE_OUTPUT_DIR="${OVERWRITE_OUTPUT_DIR:-false}"
DEEPSPEED_CONFIG="${DEEPSPEED_CONFIG:-${PROJECT_ROOT}/examples/rcpc-sft/deepspeed_zero1_offload.json}"

USER_MAX_STEPS="${MAX_STEPS:-}"
USER_MAX_SAMPLES="${MAX_SAMPLES:-}"
USER_MAX_EVAL_SAMPLES="${MAX_EVAL_SAMPLES:-}"
USER_SAVE_STEPS="${SAVE_STEPS:-}"
USER_EVAL_STEPS="${EVAL_STEPS:-}"
USER_REPORT_TO="${REPORT_TO:-}"

# Distributed layout.
TRAIN_CUDA_VISIBLE_DEVICES="${TRAIN_CUDA_VISIBLE_DEVICES:-0,1,2,3,4,5,6,7}"
export CUDA_VISIBLE_DEVICES="${TRAIN_CUDA_VISIBLE_DEVICES}"
NPROC_PER_NODE="${NPROC_PER_NODE:-8}"

# Data fields and sequence length.
PROMPT_KEY="${PROMPT_KEY:-question}"
TARGET_KEY="${TARGET_KEY:-cot}"
ANSWER_KEY="${ANSWER_KEY:-answer}"
MAX_PROMPT_LENGTH="${MAX_PROMPT_LENGTH:-8192}"
MAX_RESPONSE_LENGTH="${MAX_RESPONSE_LENGTH:-4096}"
VAL_SPLIT_SIZE="${VAL_SPLIT_SIZE:-200}"

# Training schedule and batch.
# Effective train batch = NPROC_PER_NODE * PER_DEVICE_TRAIN_BATCH_SIZE * GRADIENT_ACCUMULATION_STEPS.
# Default is 8 * 1 * 8 = 64 samples per optimizer step.
NUM_TRAIN_EPOCHS="${NUM_TRAIN_EPOCHS:-1}"
MAX_STEPS="${MAX_STEPS:--1}"
PER_DEVICE_TRAIN_BATCH_SIZE="${PER_DEVICE_TRAIN_BATCH_SIZE:-1}"
PER_DEVICE_EVAL_BATCH_SIZE="${PER_DEVICE_EVAL_BATCH_SIZE:-1}"
GRADIENT_ACCUMULATION_STEPS="${GRADIENT_ACCUMULATION_STEPS:-8}"
LEARNING_RATE="${LEARNING_RATE:-5e-6}"
WEIGHT_DECAY="${WEIGHT_DECAY:-0.01}"
WARMUP_RATIO="${WARMUP_RATIO:-0.03}"
LOGGING_STEPS="${LOGGING_STEPS:-1}"
EVAL_STEPS="${EVAL_STEPS:-20}"
SAVE_STEPS="${SAVE_STEPS:-20}"
SAVE_TOTAL_LIMIT="${SAVE_TOTAL_LIMIT:-4}"
MAX_GRAD_NORM="${MAX_GRAD_NORM:-1.0}"
MAX_SAMPLES="${MAX_SAMPLES:-0}"
MAX_EVAL_SAMPLES="${MAX_EVAL_SAMPLES:-0}"

# Model/runtime knobs.
TRUST_REMOTE_CODE="${TRUST_REMOTE_CODE:-true}"
ATTN_IMPLEMENTATION="${ATTN_IMPLEMENTATION:-flash_attention_2}"
ALLOW_ATTN_FALLBACK="${ALLOW_ATTN_FALLBACK:-true}"

# WandB. Set REPORT_TO=none to disable. WANDB_API_KEY is intentionally not
# hardcoded here; use the environment or `wandb login` on the training machine.
export WANDB__SERVICE_WAIT="${WANDB__SERVICE_WAIT:-300}"
WANDB_MODE="${WANDB_MODE:-online}"
WANDB_DIR="${WANDB_DIR:-${OUTPUT_DIR}/wandb}"
REPORT_TO="${REPORT_TO:-wandb}"
WANDB_PROJECT="${WANDB_PROJECT:-rcpc-sft}"
RUN_NAME="${RUN_NAME:-qwen3-4b-webinstruct-cot-sft}"
WANDB_NAME="${WANDB_NAME:-${RUN_NAME}}"

# SFT data robustness and qualitative generation inspection.
SFT_GRADIENT_CHECKPOINTING="${SFT_GRADIENT_CHECKPOINTING:-true}"
SFT_SKIP_BAD_SAMPLES="${SFT_SKIP_BAD_SAMPLES:-true}"
SFT_EVAL_SKIP_BAD_SAMPLES="${SFT_EVAL_SKIP_BAD_SAMPLES:-true}"
SFT_MAX_SAMPLE_RETRIES="${SFT_MAX_SAMPLE_RETRIES:-32}"
SFT_TRUNCATE_TARGET="${SFT_TRUNCATE_TARGET:-false}"
SFT_WRAP_UNTAGGED_TARGET="${SFT_WRAP_UNTAGGED_TARGET:-true}"
SFT_WRAP_QUESTION_TAGS="${SFT_WRAP_QUESTION_TAGS:-true}"
SFT_AUDIT_DATASETS="${SFT_AUDIT_DATASETS:-true}"
SFT_PRINT_GENERATION_EVERY="${SFT_PRINT_GENERATION_EVERY:-5}"
SFT_PRINT_GENERATION_COUNT="${SFT_PRINT_GENERATION_COUNT:-3}"
SFT_PRINT_GENERATION_FROM_VAL="${SFT_PRINT_GENERATION_FROM_VAL:-true}"
SFT_PRINT_GENERATION_MAX_NEW_TOKENS="${SFT_PRINT_GENERATION_MAX_NEW_TOKENS:-1024}"
SFT_PRINT_GENERATION_DO_SAMPLE="${SFT_PRINT_GENERATION_DO_SAMPLE:-false}"
SFT_PRINT_GENERATION_TEMPERATURE="${SFT_PRINT_GENERATION_TEMPERATURE:-0.0}"
SFT_PRINT_GENERATION_TOP_P="${SFT_PRINT_GENERATION_TOP_P:-1.0}"
SFT_PRINT_GENERATION_PROMPT_PREVIEW_CHARS="${SFT_PRINT_GENERATION_PROMPT_PREVIEW_CHARS:-1200}"

if [[ "${SFT_SMOKE:-0}" == "1" ]]; then
  MAX_STEPS="${USER_MAX_STEPS:-5}"
  MAX_SAMPLES="${USER_MAX_SAMPLES:-64}"
  MAX_EVAL_SAMPLES="${USER_MAX_EVAL_SAMPLES:-16}"
  SAVE_STEPS="${USER_SAVE_STEPS:-5}"
  EVAL_STEPS="${USER_EVAL_STEPS:-5}"
  REPORT_TO="${USER_REPORT_TO:-none}"
fi

export MODEL_PATH TRAIN_FILE VAL_FILE OUTPUT_DIR RESUME_FROM_CHECKPOINT OVERWRITE_OUTPUT_DIR DEEPSPEED_CONFIG
export PROMPT_KEY TARGET_KEY ANSWER_KEY MAX_PROMPT_LENGTH MAX_RESPONSE_LENGTH VAL_SPLIT_SIZE
export NUM_TRAIN_EPOCHS MAX_STEPS PER_DEVICE_TRAIN_BATCH_SIZE PER_DEVICE_EVAL_BATCH_SIZE GRADIENT_ACCUMULATION_STEPS
export LEARNING_RATE WEIGHT_DECAY WARMUP_RATIO LOGGING_STEPS EVAL_STEPS SAVE_STEPS SAVE_TOTAL_LIMIT MAX_GRAD_NORM MAX_SAMPLES MAX_EVAL_SAMPLES
export TRUST_REMOTE_CODE ATTN_IMPLEMENTATION ALLOW_ATTN_FALLBACK
export REPORT_TO WANDB_MODE WANDB_DIR WANDB_PROJECT RUN_NAME WANDB_NAME
export SFT_GRADIENT_CHECKPOINTING SFT_SKIP_BAD_SAMPLES SFT_EVAL_SKIP_BAD_SAMPLES SFT_MAX_SAMPLE_RETRIES
export SFT_TRUNCATE_TARGET SFT_WRAP_UNTAGGED_TARGET SFT_WRAP_QUESTION_TAGS SFT_AUDIT_DATASETS
export SFT_PRINT_GENERATION_EVERY SFT_PRINT_GENERATION_COUNT SFT_PRINT_GENERATION_FROM_VAL
export SFT_PRINT_GENERATION_MAX_NEW_TOKENS SFT_PRINT_GENERATION_DO_SAMPLE
export SFT_PRINT_GENERATION_TEMPERATURE SFT_PRINT_GENERATION_TOP_P SFT_PRINT_GENERATION_PROMPT_PREVIEW_CHARS

mkdir -p "${OUTPUT_DIR}" "${WANDB_DIR}"
cd "${PROJECT_ROOT}"

torchrun --standalone --nproc_per_node="${NPROC_PER_NODE}" \
  scripts/rcpc_qwen3_cot_sft_train.py \
  "$@"
